version: '3.8'
services:
    app:
        build: .
        ports:
          - "8010:8000"
          - "7861:7860"
        environment:
          - API_HOST=${API_HOST}
          - API_PORT=${API_PORT}
